[package]
name = "apibara-cli"
version = "0.1.2"
edition = "2021"

[dependencies]
apibara = { path = "../apibara" }
anyhow = "1.0"
clap = { version = "3.2", features = ["derive"] }
futures = "0.3.21"
syn = "^1.0.96"
tokio = { version = "1.18", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["std", "env-filter"] }