[package]
name = "apibara-node"
version = "0.1.0"
edition = "2021"

[dependencies]
apibara-core = { path = "../core" }
arrayvec = "0.7.2"
byteorder = "1.4.3"
clap = { version = "3.2.17", features = ["env", "unicode"] }
dirs = "4.0.0"
env_logger = "0.9.0"
futures = "0.3.23"
libmdbx = "0.1.7"
opentelemetry = { version = "0.17.0", features = ["trace", "metrics", "rt-tokio"] }
prost = "0.11.0"
prost-types = "0.11.1"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["full"] }
tracing = "0.1.36"
tracing-opentelemetry = "0.17.4"
tracing-subscriber = { version = "0.3.15", features = ["std", "env-filter"] }

[dev-dependencies]
assert_matches = "1.5.0"
env_logger = "0.9.0"
tempfile = "3.3.0"
