[package]
name = "apibara-dna-common"
version = "0.0.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "apibara_dna_common"
path = "src/lib.rs"

[dependencies]
apibara-dna-protocol = { path = "../protocol" }
async-compression.workspace = true
async-trait.workspace = true
bytes.workspace = true
byte-unit.workspace = true
clap.workspace = true
error-stack.workspace = true
flatbuffers.workspace = true
futures-util.workspace = true
hex.workspace = true
lru.workspace = true
# Make clients cloneable
object_store = { git = "https://github.com/fracek/arrow-rs", rev = "52ec42ac", features = [
    "aws",
    "azure",
] }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tonic.workspace = true
tonic-reflection.workspace = true
tracing.workspace = true

[dev-dependencies]
azure_storage = "0.19.0"
azure_storage_blobs = "0.19.0"
tempdir.workspace = true
nanoid.workspace = true
reqwest.workspace = true
testcontainers.workspace = true

[build-dependencies]
pbjson-build.workspace = true
tonic-build.workspace = true
